const SOCKET_IDS = {
  SEND_TX: 1,
  GET_LEADERBOARD: 2,
  GET_PROFILE: 3,
  SET_PROFILE: 4,
  REDEEM_REWARDS: 5,
  EMAIL_INVITE: 6,
  GET_CHAINS: 7,
  NOTIFICATION: 8,
  NOTIFICATION_MARK_AS_READ: 9,
  GET_TX_HISTORY: 10,
  TWIITER_USERNAME_TO_ID: 11,
  TWITTER_ID_TO_USERNAME: 12,
  PING: 255,
};

const LEADERBOARD_TYPES = {
  GLOBAL: "g".charCodeAt(0),
  WEEKLY: "w".charCodeAt(0),
};

export { SOCKET_IDS, LEADERBOARD_TYPES };
